"""pg_catalog 内省（设计文档 §4.3）。

数据库是唯一事实来源：这里提供的查询是 agent 认识 schema 的唯一途径。
两级策略：list_tables 鸟瞰 → inspect_tables 按表详情（对抗上下文膨胀 C-6）。
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

import psycopg

_SYSTEM_SCHEMAS = ["pg_catalog", "information_schema"]  # list：psycopg3 将 list 适配为 PG 数组


@dataclass(frozen=True)
class TableSummary:
    schema: str
    name: str
    columns: int
    row_estimate: int
    size_bytes: int

    @property
    def qualified(self) -> str:
        return f"{self.schema}.{self.name}"

    @property
    def human_size(self) -> str:
        size = float(self.size_bytes)
        for unit in ("B", "KB", "MB", "GB", "TB"):
            if size < 1024 or unit == "TB":
                return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
            size /= 1024
        return f"{size:.1f} TB"


def list_tables(conn: psycopg.Connection) -> list[TableSummary]:
    rows = conn.execute(
        """
        SELECT n.nspname,
               c.relname,
               (SELECT count(*) FROM pg_attribute a
                 WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped),
               GREATEST(c.reltuples, 0)::bigint,
               pg_total_relation_size(c.oid)
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r', 'p')
          AND NOT (n.nspname = ANY(%s))
          AND n.nspname NOT LIKE 'pg_%%'
          AND c.relname <> 'agent_schema_migrations'
        ORDER BY 1, 2
        """,
        (_SYSTEM_SCHEMAS,),
    ).fetchall()
    return [
        TableSummary(schema=r[0], name=r[1], columns=r[2], row_estimate=r[3], size_bytes=r[4])
        for r in rows
    ]


def inspect_tables(conn: psycopg.Connection, names: list[str]) -> tuple[list[str], list[str]]:
    """渲染指定表的结构为紧凑 DDL。

    返回 (found_ddl_parts, missing_names)：missing 用于对抗模型幻觉——
    引用不存在的表会在此暴露，而不是等到执行阶段。
    """
    parts: list[str] = []
    missing: list[str] = []

    for name in names:
        table = _find_table(conn, name)
        if table is None:
            missing.append(name)
            continue
        schema, relname = table
        rows = conn.execute(
            """
            SELECT a.attname,
                   pg_catalog.format_type(a.atttypid, a.atttypmod),
                   a.attnotnull,
                   a.attidentity,
                   a.attgenerated,
                   pg_get_expr(d.adbin, d.adrelid)
            FROM pg_attribute a
            LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
            WHERE a.attrelid = %s::regclass AND a.attnum > 0 AND NOT a.attisdropped
            ORDER BY a.attnum
            """,
            (f"{schema}.{relname}",),
        ).fetchall()
        col_lines = []
        for col, typ, notnull, identity, generated, default in rows:
            piece = f"    {col} {typ}"
            if identity == "a":
                piece += " GENERATED ALWAYS AS IDENTITY"
            elif identity == "d":
                piece += " GENERATED BY DEFAULT AS IDENTITY"
            if generated == "s":
                piece += f" GENERATED ALWAYS AS ({default})"
            elif default and not identity and not generated:
                piece += f" DEFAULT {default}"
            if notnull:
                piece += " NOT NULL"
            col_lines.append(piece)

        cons = conn.execute(
            """
            SELECT conname, pg_get_constraintdef(oid)
            FROM pg_constraint
            WHERE conrelid = %s::regclass AND contype IN ('p', 'f', 'u', 'c')
            ORDER BY conname
            """,
            (f"{schema}.{relname}",),
        ).fetchall()
        for conname, condef in cons:
            col_lines.append(f"    CONSTRAINT {conname} {condef}")

        cols_sql = ",\n".join(col_lines)
        parts.append(f"CREATE TABLE {schema}.{relname} (\n{cols_sql}\n);")

        idx_rows = conn.execute(
            """
            SELECT pg_get_indexdef(i.indexrelid)
            FROM pg_index i
            JOIN pg_class ic ON ic.oid = i.indexrelid
            WHERE i.indrelid = %s::regclass
              AND NOT i.indisprimary
              AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = ic.oid)
            ORDER BY ic.relname
            """,
            (f"{schema}.{relname}",),
        ).fetchall()
        parts.extend(r[0] + ";" for r in idx_rows)

    return parts, missing


def table_row_estimates(conn: psycopg.Connection) -> dict[str, int]:
    """全部表的行数估计（小写表名 → 行数），供风险引擎的大表规则使用。"""
    return {
        r[0].lower(): max(int(r[1]), 0)
        for r in conn.execute(
            """
            SELECT c.relname, c.reltuples
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'p') AND NOT (n.nspname = ANY(%s))
              AND n.nspname NOT LIKE 'pg_%%'
          AND c.relname <> 'agent_schema_migrations'
            """,
            (_SYSTEM_SCHEMAS,),
        ).fetchall()
    }


def schema_fingerprint(conn: psycopg.Connection) -> str:
    """结构指纹：表/列/约束/索引的规范化哈希，用于漂移检测（FR-10）。"""
    rows = conn.execute(
        """
        SELECT n.nspname, c.relname, a.attnum, a.attname,
               pg_catalog.format_type(a.atttypid, a.atttypmod), a.attnotnull,
               COALESCE(pg_get_expr(d.adbin, d.adrelid), ''),
               COALESCE((SELECT string_agg(conname || ':' || pg_get_constraintdef(oid), '||'
                                          ORDER BY conname)
                         FROM pg_constraint con WHERE con.conrelid = c.oid
                           AND contype IN ('p','f','u','c')), ''),
               COALESCE((SELECT string_agg(pg_get_indexdef(indexrelid), '||' ORDER BY indexrelid)
                         FROM pg_index i WHERE i.indrelid = c.oid), '')
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
        LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        WHERE c.relkind IN ('r','p') AND NOT (n.nspname = ANY(%s))
          AND n.nspname NOT LIKE 'pg_%%'
          AND c.relname <> 'agent_schema_migrations'
        ORDER BY 1, 2, 3
        """,
        (_SYSTEM_SCHEMAS,),
    ).fetchall()
    canonical = "\n".join("|".join("" if v is None else str(v) for v in row) for row in rows)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _find_table(conn: psycopg.Connection, name: str) -> tuple[str, str] | None:
    """按名找表；支持 schema.table 全限定名，否则在非系统 schema 中查找。"""
    if "." in name:
        schema, relname = name.split(".", 1)
    else:
        schema, relname = None, name
    rows = conn.execute(
        """
        SELECT n.nspname, c.relname
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r', 'p')
          AND c.relname = %s
          AND NOT (n.nspname = ANY(%s))
          AND n.nspname NOT LIKE 'pg_%%'
          AND c.relname <> 'agent_schema_migrations'
          AND (%s::text IS NULL OR n.nspname = %s::text)
        """,
        (relname, _SYSTEM_SCHEMAS, schema, schema),
    ).fetchall()
    if not rows:
        return None
    return str(rows[0][0]), str(rows[0][1])
